### ISSUE TITLE
Telegram Bot Airdrop Automation

### ISSUE THREAD

**Issue by shfatislam** [svtcore/telegram-user-comments#1]
Hello Bro can you hack this telegram bot game 

https://t.me/catizenbot/gameapp?startapp=r_3_3254911

This is a earning game can you hack 

![Screenshot_20240424_233429_Telegram](https://github.com/svtcore/telegram-user-comments/assets/129420596/9afd80c1-c64f-4f47-b94b-a9802507a739)
![Screenshot_20240424_233502_Telegram](https://github.com/svtcore/telegram-user-comments/assets/129420596/971f4a6a-ab1f-4ef0-b3e4-3691f0ea0b93)
![Screenshot_20240424_233535_Telegram](https://github.com/svtcore/telegram-user-comments/assets/129420596/a323b102-7b87-47d9-b52b-d84dec7871fe)

And if you can't hack the game then can you make auto bot for this game.  I am giving you the screenshots for you to check them out

And to buy autobots for this game you need 3900 fish tokens which is worth about 12 dollars.  And I joined here with 13 telegram accounts so it is not possible for me to buy this auto bot for each account with so many dollars.  So can you make an auto bot for it or hack the game itself?  Don't forget to let me know if you can.

**Comment by svtcore** [comment]
Hi, looks like you have posted wrong issue in the wrong repository. If you want automate inviting your accounts to bot I recommend use another bot [telegram-referral-bot](https://github.com/svtcore/telegram-referral-bot). It could help you invite your telegram accounts with your invite code.
